#!/bin/sh

# Uses https://github.com/b4n/ctags/tree/better-php-parser

set -e
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -R -f.git/tags.$$ --exclude=.git --fields=+aimS --languages=php .
mv .git/tags.$$ .git/tags
